python: "3.10"
# Dependencies required to build packages. This field is optional.
build_dependencies:
  - pip
  - setuptools
  - wheel==0.37.1

dependencies:
  - pytest
  - black
  - pylint
  - pytest
  - bandit
  - mypy
  - setuptools
  - mlflow
  - torch
  - torchvision
  - types-requests