[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'
skip-string-normalization = true

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
disallow_any_unimported = false
no_implicit_optional = true
ignore_missing_imports = true

[tool.pytest.ini_options]